### PR TITLE
basic ui update (icon/home page)

### LINKED ISSUE #12: [Design]: Logo
Logo of the brand

### PR DESCRIPTION
**Pull request by turn-a-round**
---
name: Pull Request
about: UI
title: '✍️ basic ui update (icon/home page)'
labels: ''
assignees: '@turn-a-round'
---
| Feature  | Bug/Feature Title       | Branch From            | Branch To |
| ------------ | ----------------------- | ---------------------- | --------- |
| #12  | Feature: basic ui update (icon/home page) | design/basic-ui | master    |

**Additional context**

- new icon.
logo
- homepage design
home_page

### CODE REVIEW

**Comment by ChinmoyJana14** [comment]
logo is ok

**Comment by ChinmoyJana14** [comment]
black screen is not attractive; also the font

**Comment by turn-a-round** [comment]
Don't close it without merge completion if it's still relevant...

**Comment by turn-a-round** [comment]
> black screen is not attractive; also the font

It's Dark mode design sample & unfortunately Pencil doesn't support custom fonts.
Check the fonts in assets/fonts & check the pubspec.yaml for font details

**Comment by ChinmoyJana14** [comment]
> > black screen is not attractive; also the font
> 
> It's Dark mode design sample & unfortunately Pencil doesn't support custom fonts.
> Check the fonts in assets/fonts & check the pubspec.yaml for font details

Unable to preview the yaml file, tried in swagger editor as well as vs code

**Comment by turn-a-round** [comment]
> > > black screen is not attractive; also the font
> > 
> > 
> > It's Dark mode design sample & unfortunately Pencil doesn't support custom fonts.
> > Check the fonts in assets/fonts & check the pubspec.yaml for font details
> 
> Unable to preview the yaml file, tried in swagger editor as well as vs code

All yaml files are not swagger file :P

**Review by ChinmoyJana14 — APPROVED** [review]

**Pull request merged**
